redis:
  host: localhost
  port: 6379
  password:
output:
  dir: output
  file: index.html
template:
  info: template_info.html
  html_head: template_head.html
  log: template_log.html
time:
  format: 2006-01-02 15:04:05 MST
  timezone: UTC
relay_log:
  path: /home/claire/activity-relay/logs/server.log
  offset: 0