redis:
  host: localhost
  port: 6379
  password:
output:
  dir: output
  file: index.html
template:
  markdown: template.md
  html_head: template_head.html
time:
  format: 2006-01-02 15:04:05 MST
  timezone: UTC